package be.xplore.notifyme.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * Object representation of an address (location in the world).
 */
@Entity
@Getter
@Setter
@RequiredArgsConstructor
public class Address {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private long id;
  private String streetAndNumber;
  private String postalCode;
  private String village;
  private String country;

  /**
   * Default constructor without autogenerated ID.
   *
   * @param streetAndNumber street and number
   * @param postalCode      postalcode
   * @param village         village/city
   * @param country         country
   */
  public Address(String streetAndNumber, String postalCode, String village, String country) {
    this.streetAndNumber = streetAndNumber;
    this.postalCode = postalCode;
    this.village = village;
    this.country = country;
  }
}
