server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb

keycloak:
  server:
    contextPath: /auth
    adminUsername: admin
    adminPassword: admin
    realmImportFile: notifyme-realm.json
